name: Sync n8n Knowledge Base

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: sync-knowledge-base
  cancel-in-progress: true

jobs:
  sync-all-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 1. Официальная документация n8n
      - name: Sync n8n Official Docs
        uses: actions/checkout@v4
        with:
          repository: n8n-io/n8n-docs
          path: ./temp/official-docs

      # 2. Крупнейшая коллекция workflow (2000+)
      - name: Sync Zie619 Workflows
        uses: actions/checkout@v4
        with:
          repository: Zie619/n8n-workflows
          path: ./temp/zie619-workflows

      # 3. AI-фокусированные темплейты (200+)
      - name: Sync WassupJay Templates
        uses: actions/checkout@v4
        with:
          repository: wassupjay/n8n-free-templates
          path: ./temp/wassupjay-templates

      # 4. LLM-оптимизированная документация
      - name: Sync Awesome n8n
        uses: actions/checkout@v4
        with:
          repository: Synaptiv-AI/awesome-n8n
          path: ./temp/awesome-n8n

      # 5. Профессиональные workflow
      - name: Sync ProfSynapse Automations
        uses: actions/checkout@v4
        with:
          repository: ProfSynapse/n8n-automations
          path: ./temp/profsynapse

      # 6. Обновляем локальную базу знаний
      - name: Update Knowledge Base
        run: |
          set -e
          mkdir -p docs examples community llm-docs

          # Копируем официальную документацию
          if [ -d "./temp/official-docs/docs" ]; then
            cp -r ./temp/official-docs/docs/* ./docs/ 2>/dev/null || true
          fi

          # Копируем workflow коллекции
          if [ -d "./temp/zie619-workflows" ]; then
            find ./temp/zie619-workflows -name "*.json" -exec cp {} ./examples/ \; 2>/dev/null || true
          fi

          if [ -d "./temp/wassupjay-templates" ]; then
            find ./temp/wassupjay-templates -name "*.json" -exec cp {} ./examples/ \; 2>/dev/null || true
          fi

          if [ -d "./temp/profsynapse" ]; then
            find ./temp/profsynapse -name "*.json" -exec cp {} ./examples/ \; 2>/dev/null || true
          fi

          # Специальные файлы для LLM
          if [ -f "./temp/awesome-n8n/n8n-docs-llms.txt" ]; then
            cp ./temp/awesome-n8n/n8n-docs-llms.txt ./llm-docs/
          fi

          # Очищаем временные файлы
          rm -rf ./temp

          # Создаем метаданные
          echo "Last updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > ./LAST_SYNC.md
          echo "Total workflow files: $(find ./examples -name "*.json" | wc -l)" >> ./LAST_SYNC.md

      # 6b. Санитизация потенциальных секретов в примерах (во избежание блокировки Push Protection)
      - name: Sanitize examples (remove tokens)
        run: |
          set -e
          sanitize_dir() {
            target_dir="$1"
            [ -d "$target_dir" ] || return 0

            # Apify tokens
            files=$(grep -RIl 'apify_api_' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/apify_api_[A-Za-z0-9]+/<REDACTED_APIFY_TOKEN>/g'

            # Slack tokens
            files=$(grep -RIlE 'xox[abprs]-[A-Za-z0-9-]+' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/xox[abprs]-[A-Za-z0-9-]+/<REDACTED_SLACK_TOKEN>/g'

            # Telegram bot tokens
            files=$(grep -RIlE '[0-9]{9,}:[A-Za-z0-9_-]{35,}' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/[0-9]{9,}:[A-Za-z0-9_-]{35,}/<REDACTED_TELEGRAM_TOKEN>/g'

            # Discord webhooks
            files=$(grep -RIlE 'https://discord\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's#https://discord\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+#<REDACTED_DISCORD_WEBHOOK>#g'

            # OpenAI keys
            files=$(grep -RIlE 'sk-[A-Za-z0-9_-]{20,}' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/sk-[A-Za-z0-9_-]{20,}/<REDACTED_OPENAI_KEY>/g'

            # GitHub tokens
            files=$(grep -RIlE '(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,}' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,}/<REDACTED_GITHUB_TOKEN>/g'

            # Google API keys
            files=$(grep -RIlE 'AIza[0-9A-Za-z\-_]{35}' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/AIza[0-9A-Za-z\-_]{35}/<REDACTED_GOOGLE_API_KEY>/g'

            # Notion tokens
            files=$(grep -RIlE 'secret_[A-Za-z0-9]{43,}' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/secret_[A-Za-z0-9]{43,}/<REDACTED_NOTION_TOKEN>/g'

            # Hugging Face tokens
            files=$(grep -RIlE 'hf_[A-Za-z0-9]{38,}' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/hf_[A-Za-z0-9]{38,}/<REDACTED_HF_TOKEN>/g'

            # AWS access keys
            files=$(grep -RIlE 'AKIA[0-9A-Z]{16}' "$target_dir" || true)
            [ -n "$files" ] && echo "$files" | xargs -r sed -i -E 's/AKIA[0-9A-Z]{16}/<REDACTED_AWS_ACCESS_KEY>/g'
          }

          sanitize_dir ./examples
          sanitize_dir ./docs

      # 7. Пытаемся запушить изменения напрямую в main
      - name: Auto-commit updates to main
        id: autopush
        continue-on-error: true
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git pull --ff-only origin main
          git add -A
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          git commit -m "🤖 Auto-sync: n8n knowledge base updates"
          if git push origin HEAD:main; then
            echo "pushed=true" >> $GITHUB_OUTPUT
          fi

      # 8. Создаем Pull Request, если прямой пуш не получился
      - name: Create Pull Request
        id: cpr
        if: steps.autopush.outputs.pushed != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Auto-sync: n8n knowledge base updates"
          branch: chore/auto-sync-knowledge-base
          title: "🤖 Auto-sync: n8n knowledge base updates"
          body: |
            This PR updates docs/examples from upstream sources.
            - See LAST_SYNC.md for details.
            - Sources: n8n-io/n8n-docs, Zie619/n8n-workflows, wassupjay/n8n-free-templates, Synaptiv-AI/awesome-n8n, ProfSynapse/n8n-automations.
          labels: automated, sync
          delete-branch: true

      # 9. Включаем авто-merge для PR (если репозиторий это позволяет)
      - name: Enable PR auto-merge
        if: steps.autopush.outputs.pushed != 'true' && steps.cpr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
