version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      # n8n настройки
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_EXPERIMENTAL_AI_ENABLE=true
      
      # Workflow IDs
      - WF_01_WORKFLOW_ID=${WF_01_WORKFLOW_ID}
      - WF_02_WORKFLOW_ID=${WF_02_WORKFLOW_ID}
      - WF_03_WORKFLOW_ID=${WF_03_WORKFLOW_ID}
      - WF_04_WORKFLOW_ID=${WF_04_WORKFLOW_ID}
      - WF_05_WORKFLOW_ID=${WF_05_WORKFLOW_ID}
      - WF_06_WORKFLOW_ID=${WF_06_WORKFLOW_ID}
      
      # Google Sheets
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      
      # Telegram
      - TELEGRAM_ADMIN_CHAT_ID=${TELEGRAM_ADMIN_CHAT_ID}
      
      # API Keys
      - YANDEX_MAPS_API_KEY=${YANDEX_MAPS_API_KEY}
      - TWOGIS_API_KEY=${TWOGIS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BITRIX24_WEBHOOK_URL=${BITRIX24_WEBHOOK_URL}
      
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - n8n-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - n8n-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - n8n-network

volumes:
  n8n_data:
  qdrant_data:

networks:
  n8n-network:
    driver: bridge